# Generated by Django 3.0.2 on 2020-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles__api', '0002_profilefeeditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
