# Generated by Django 3.0.2 on 2020-01-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles__api', '0003_profilefeeditems_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItems',
        ),
    ]
