# Generated by Django 3.0.2 on 2020-01-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles__api', '0005_userprofile_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='fullname',
        ),
    ]
